services:
  adapter:
    image: node:20
    volumes:
      - .:/home/node/sails-mongo
    depends_on:
      - mongo
    environment:
      - WATERLINE_ADAPTER_TESTS_DATABASE=sails-mongo
      - WATERLINE_ADAPTER_TESTS_URL=mongo:27017/testdb
      - WATERLINE_ADAPTER_TESTS_HOST=mongo
      - MONGO_PORT=27017
      - NODE_ENV=test
    user: node
    working_dir: /home/node/sails-mongo
    command:
      - bash
      - -c
      - "npm test"

  mongo:
    image: mongo:8.0
    restart: always
    command: "--logpath=/dev/null"
    ports:
      - "27018:27017"
